// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSudoku() {
  return window['go']['main']['App']['GetSudoku']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitCell'](arg1, arg2, arg3);
}

export function LockCells() {
  return window['go']['main']['App']['LockCells']();
}

export function NewSudoku(arg1) {
  return window['go']['main']['App']['NewSudoku'](arg1);
}

export function UnlockCells() {
  return window['go']['main']['App']['UnlockCells']();
}
