// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSudoku():Promise<main.Sudoku>;

export function Greet(arg1:string):Promise<string>;

export function InitCell(arg1:number,arg2:number,arg3:number):Promise<void>;

export function LockCells():Promise<any>;

export function NewSudoku(arg1:number):Promise<void>;

export function UnlockCells():Promise<any>;
